version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    environment:
      CLOUDSDK_CORE_PROJECT: domino-eng-platform-dev
      CLOUDSDK_COMPUTE_ZONE: us-west1-a
      GOOGLE_APPLICATION_CREDENTIALS: /root/.config/gcloud/legacy_credentials/terraform-gke-test@domino-eng-platform-dev.iam.gserviceaccount.com/adc.json
      TERRAFORM_VERSION: 1.0.6

    steps:
      - checkout

      - run:
          name: Install Terraform
          command: |
            apt-get install -y wget zip
            wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
            unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin

      - run:
          name: Configure test cluster env
          command: |
            echo 'export TF_VAR_description="CircleCI Build for ${CIRCLE_PR_REPONAME}: ${CIRCLE_BUILD_URL}"' >> $BASH_ENV
            echo 'export TF_VAR_filestore_disabled="true"' >> $BASH_ENV
            echo 'export GOOGLE_CREDENTIALS="$CLOUDSDK_SERVICE_KEY"' >> $BASH_ENV
            echo 'export WORKSPACE=gcp-gke-circleci-${CIRCLE_BUILD_NUM}' >> $BASH_ENV

      - run:
          name: Terraform fmt
          command: terraform fmt -check

      - run:
          name: Test Terraform
          command: |
            cd tests
            terraform init
            terraform validate
            terraform workspace new ${WORKSPACE}
            terraform apply -auto-approve
            terraform plan -detailed-exitcode

      - run:
          name: Terraform destroy
          command: |
            cd tests
            terraform destroy -auto-approve || (sleep 5m && terraform destroy -auto-approve)
          when: always

      - run:
          name: Terraform workspace delete
          command: |
            cd tests
            terraform workspace select default
            terraform workspace delete ${WORKSPACE}
          when: always
